alias ga="git add"
alias gA="git add -A :/"
alias gc="git checkout"
alias gC="git commit"
alias gAC="gA && gC"
alias gp="git pull --rebase"
alias gP="git push"
alias gr="git rebase"
alias gs="git status"
alias gd="git diff"
alias gl="git log --pretty=format:\"%C(auto)%h %<(8,trunc)%aN %Cgreen%s %n%w(80,17,17)%-b\""
alias gm="git merge"

