
" Plugins {{{
call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'chriskempson/base16-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mattn/emmet-vim'
Plug 'vim-airline/vim-airline'
Plug 'kchmck/vim-coffee-script'
Plug 'tmhedberg/matchit'
Plug 'tpope/vim-surround'
Plug 'scrooloose/nerdtree'
call plug#end()
" }}}

" Plugin Configuration {{{

" Airline
set laststatus=2 " Always show a status line at the bottom

" CtrlP
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

" NERDTree
map <C-n> :NERDTreeToggle<CR>

" }}}

" Theme {{{
syntax enable
set background=dark
colorscheme gruvbox

" Reset background colors to transparent
hi Normal ctermbg=none
hi None ctermbg=none
"}}}

" Enable filetype plugins
filetype plugin on
filetype indent on

set number " Show line numbers in left gutter
set ruler " Display the current line and column
set showmatch " Highlight matching brackets
set nowrap " Don't soft wrap lines
set noerrorbells visualbell t_vb= " Disable all errorbells
set mouse=a " Enable using the mouse

" Allow modelines at the top or bottom of files
set modeline
set modelines=5

" Enable autocompletion of vim-commands
set wildmenu
set wildmode=longest:list,full
set wildignore+=*/node_modules/*
set wildignore+=*/bower_components/*

" Use 2 spaces for indentation
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Allow for saving/quitting with lazy shift key
command! W w
command! Q q
command! Wq wq
command! WQ wq
command! Reload so $MYVIMRC


" Set folding by marker for this file only
" vim:foldmethod=marker
