" Plugins loaded by vim-plug
call plug#begin()
Plug 'morhetz/gruvbox'
call plug#end()

" Styling
syntax enable
set background=dark
colorscheme gruvbox

" Reset background colors to transparent
hi Normal ctermbg=none
hi None ctermbg=none

" Enable filetype plugins
filetype plugin on
filetype indent on

set number " Show line numbers in left gutter
set ruler " Display the current line and column
set showmatch " Highlight matching brackets
set nowrap " Don't soft wrap lines
set noerrorbells visualbell t_vb= " Disable all errorbells
set mouse=a " Enable using the mouse

" Enable autocompletion of vim-commands
set wildmenu
set wildmode=longest:list,full

" Use 2 spaces for indentation
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Allow for saving/quitting with lazy shift key
command W w
command Q q
command Wq wq
command WQ wq
